# Generated by Django 2.2.3 on 2019-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('source_link', models.URLField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Pending', 'Pending'), ('Try again?', 'Try Again'), ('YAY!', 'Completed'), ("You didn't like this quiz!", 'Not Submitted')], default='Ongoing', max_length=50)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
