# Generated by Django 2.2.3 on 2019-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
