# Generated by Django 2.2.3 on 2019-07-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20190728_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizForEY',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.Quiz')),
                ('answer', models.ImageField(blank=True, null=True, upload_to='answer_ey/%Y/%m/%d/')),
            ],
            bases=('quizzes.quiz',),
        ),
        migrations.CreateModel(
            name='QuizForSY',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.Quiz')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            bases=('quizzes.quiz',),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('quiz_for_EY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizForEY')),
                ('quiz_for_SY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizForSY')),
            ],
        ),
    ]
