# Generated by Django 2.2.3 on 2019-08-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20190728_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizforey',
            options={'verbose_name': 'Quiz For Eunyoung', 'verbose_name_plural': 'Quizzes For Eunyoung'},
        ),
        migrations.AlterModelOptions(
            name='quizforsy',
            options={'verbose_name': 'Quiz For Sungyeon', 'verbose_name_plural': 'Quizzes For Sungyeon'},
        ),
    ]
