# Generated by Django 2.2.3 on 2019-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20190809_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='source_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
