# Generated by Django 2.2.3 on 2019-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20190810_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Attempted', 'Attempted'), ('Try again?', 'Try Again'), ('Solved', 'Completed'), ("You didn't like this quiz!", 'Not Submitted')], default='Ongoing', max_length=50),
        ),
    ]
