# Generated by Django 2.2.3 on 2019-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20190821_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
