# Generated by Django 2.2.3 on 2019-08-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_auto_20190821_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='is_bonus',
        ),
    ]
