# Generated by Django 2.2.3 on 2019-08-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_remove_bundle_is_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='start_date',
        ),
    ]
