# Generated by Django 2.2.3 on 2019-08-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_auto_20190821_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='quiz_for_EY',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='quiz_for_SY',
        ),
    ]
