# Generated by Django 2.2.3 on 2019-08-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_auto_20190821_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='quiz_for_EY',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizForEY'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='quiz_for_SY',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizForSY'),
        ),
    ]
